language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install:
- gem install bundler
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: YuvIfpvsh5I1tCo9DeVtLLukwVaheKPOn2WK4OiIgNrqU1ZhFKl/Xuq3g5PJXdbgEwDAeAx6eP/AaX9Qh8g9nsk/zZ2fw22/laMy0gFhRX62w35ySNBRwsoueavVpNTbfXpksP97xoZpmDLyZtcFYszKbCL8ZdgwCyU/OTu4kjEdORVShUlZpSxZr3A9yriQUwl87pE6Hy/0z6vEH+ZYIUaFIWlCc+0CrTu5AOIEoH2fqI7vZT3+/dkInOQWHh2jQkZq9YSnfAt3pZA9h4zamQIrsDYLCYyyYadRhLNyvPrK/VxjLRSeqhsuvaGZ9OWq1ISBShFz6EMaEhViXESIMVu3D3PZJoCjYY0jEcvgXpsBzudCTQPJW5uEgfqk5cAgTE8pqs5OkJQzJiyChyR/RgDOLjbaAFCKSRExDxu5Xgq6+l0+W29SDDjN6THqzoBtoE/4sKIoum73rQFSMvVQ7ZL1uZf5m7BdYGYKIsIkPsBXdbc+3EU7IGLsY6ofzmTwggGA7k8D+7Rb96zpso/SgCmj0sLExlxicqHe495kwK9FSFb55jJJ0r86MAqMaFg01QTkAHygE2upokoFarc1WNl6PjC5/tyaST0eV9hJRideaJ400pSpLAkvB9LNFh9OXoDOU553bF6W3iozmoc0r9WJItZthHuBEGwJhdhSpmw=
  app: weathervine-be
  on:
    repo: WeatherVine/back_end
    branch: main
  skip_cleanup: 'true'
